// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.7.1
// source: proto/msg_version.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Services    uint64   `protobuf:"varint,2,opt,name=services,proto3" json:"services,omitempty"`
	Timestamp   int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AddrRecv    *NetAddr `protobuf:"bytes,4,opt,name=addr_recv,json=addrRecv,proto3" json:"addr_recv,omitempty"`
	AddrFrom    *NetAddr `protobuf:"bytes,5,opt,name=addr_from,json=addrFrom,proto3" json:"addr_from,omitempty"`
	Nonce       uint64   `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	UserAgent   *VarStr  `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	StartHeight int32    `protobuf:"varint,8,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	Relay       bool     `protobuf:"varint,9,opt,name=relay,proto3" json:"relay,omitempty"`
}

func (x *MsgVersion) Reset() {
	*x = MsgVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_version_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVersion) ProtoMessage() {}

func (x *MsgVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_version_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVersion.ProtoReflect.Descriptor instead.
func (*MsgVersion) Descriptor() ([]byte, []int) {
	return file_proto_msg_version_proto_rawDescGZIP(), []int{0}
}

func (x *MsgVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MsgVersion) GetServices() uint64 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *MsgVersion) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MsgVersion) GetAddrRecv() *NetAddr {
	if x != nil {
		return x.AddrRecv
	}
	return nil
}

func (x *MsgVersion) GetAddrFrom() *NetAddr {
	if x != nil {
		return x.AddrFrom
	}
	return nil
}

func (x *MsgVersion) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MsgVersion) GetUserAgent() *VarStr {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

func (x *MsgVersion) GetStartHeight() int32 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *MsgVersion) GetRelay() bool {
	if x != nil {
		return x.Relay
	}
	return false
}

type VarStr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Str    string `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *VarStr) Reset() {
	*x = VarStr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_msg_version_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarStr) ProtoMessage() {}

func (x *VarStr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_version_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarStr.ProtoReflect.Descriptor instead.
func (*VarStr) Descriptor() ([]byte, []int) {
	return file_proto_msg_version_proto_rawDescGZIP(), []int{1}
}

func (x *VarStr) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *VarStr) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_proto_msg_version_proto protoreflect.FileDescriptor

var file_proto_msg_version_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x1a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x02, 0x0a, 0x0a, 0x4d, 0x73,
	0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x52, 0x65, 0x63, 0x76, 0x12, 0x2e, 0x0a, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x56, 0x61, 0x72, 0x53, 0x74, 0x72, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x32, 0x0a, 0x06,
	0x56, 0x61, 0x72, 0x53, 0x74, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75,
	0x77, 0x65, 0x7a, 0x75, 0x6b, 0x77, 0x65, 0x63, 0x68, 0x69, 0x62, 0x75, 0x7a, 0x6f, 0x72, 0x2f,
	0x62, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x68, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_msg_version_proto_rawDescOnce sync.Once
	file_proto_msg_version_proto_rawDescData = file_proto_msg_version_proto_rawDesc
)

func file_proto_msg_version_proto_rawDescGZIP() []byte {
	file_proto_msg_version_proto_rawDescOnce.Do(func() {
		file_proto_msg_version_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_msg_version_proto_rawDescData)
	})
	return file_proto_msg_version_proto_rawDescData
}

var file_proto_msg_version_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_msg_version_proto_goTypes = []interface{}{
	(*MsgVersion)(nil), // 0: protocol.MsgVersion
	(*VarStr)(nil),     // 1: protocol.VarStr
	(*NetAddr)(nil),    // 2: protocol.NetAddr
}
var file_proto_msg_version_proto_depIdxs = []int32{
	2, // 0: protocol.MsgVersion.addr_recv:type_name -> protocol.NetAddr
	2, // 1: protocol.MsgVersion.addr_from:type_name -> protocol.NetAddr
	1, // 2: protocol.MsgVersion.user_agent:type_name -> protocol.VarStr
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_msg_version_proto_init() }
func file_proto_msg_version_proto_init() {
	if File_proto_msg_version_proto != nil {
		return
	}
	file_proto_net_addr_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_msg_version_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_msg_version_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarStr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_msg_version_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_version_proto_goTypes,
		DependencyIndexes: file_proto_msg_version_proto_depIdxs,
		MessageInfos:      file_proto_msg_version_proto_msgTypes,
	}.Build()
	File_proto_msg_version_proto = out.File
	file_proto_msg_version_proto_rawDesc = nil
	file_proto_msg_version_proto_goTypes = nil
	file_proto_msg_version_proto_depIdxs = nil
}
