// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.7.1
// source: proto/net_addr.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network address
type NetAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     uint32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Services uint64 `protobuf:"varint,2,opt,name=services,proto3" json:"services,omitempty"`
	Ip       *IPv4  `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port     uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *NetAddr) Reset() {
	*x = NetAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_net_addr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetAddr) ProtoMessage() {}

func (x *NetAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_addr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetAddr.ProtoReflect.Descriptor instead.
func (*NetAddr) Descriptor() ([]byte, []int) {
	return file_proto_net_addr_proto_rawDescGZIP(), []int{0}
}

func (x *NetAddr) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *NetAddr) GetServices() uint64 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *NetAddr) GetIp() *IPv4 {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *NetAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// IPv4 address
type IPv4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // Store as a byte array
}

func (x *IPv4) Reset() {
	*x = IPv4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_net_addr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPv4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4) ProtoMessage() {}

func (x *IPv4) ProtoReflect() protoreflect.Message {
	mi := &file_proto_net_addr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4.ProtoReflect.Descriptor instead.
func (*IPv4) Descriptor() ([]byte, []int) {
	return file_proto_net_addr_proto_rawDescGZIP(), []int{1}
}

func (x *IPv4) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

var File_proto_net_addr_proto protoreflect.FileDescriptor

var file_proto_net_addr_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x6d, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x49, 0x50, 0x76, 0x34, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x16, 0x0a, 0x04, 0x49, 0x50, 0x76, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x77, 0x65, 0x7a, 0x75, 0x6b, 0x77, 0x65, 0x63, 0x68,
	0x69, 0x62, 0x75, 0x7a, 0x6f, 0x72, 0x2f, 0x62, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x2d, 0x6e,
	0x6f, 0x64, 0x65, 0x2d, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_net_addr_proto_rawDescOnce sync.Once
	file_proto_net_addr_proto_rawDescData = file_proto_net_addr_proto_rawDesc
)

func file_proto_net_addr_proto_rawDescGZIP() []byte {
	file_proto_net_addr_proto_rawDescOnce.Do(func() {
		file_proto_net_addr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_net_addr_proto_rawDescData)
	})
	return file_proto_net_addr_proto_rawDescData
}

var file_proto_net_addr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_net_addr_proto_goTypes = []interface{}{
	(*NetAddr)(nil), // 0: protocol.NetAddr
	(*IPv4)(nil),    // 1: protocol.IPv4
}
var file_proto_net_addr_proto_depIdxs = []int32{
	1, // 0: protocol.NetAddr.ip:type_name -> protocol.IPv4
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_net_addr_proto_init() }
func file_proto_net_addr_proto_init() {
	if File_proto_net_addr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_net_addr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_net_addr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPv4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_net_addr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_net_addr_proto_goTypes,
		DependencyIndexes: file_proto_net_addr_proto_depIdxs,
		MessageInfos:      file_proto_net_addr_proto_msgTypes,
	}.Build()
	File_proto_net_addr_proto = out.File
	file_proto_net_addr_proto_rawDesc = nil
	file_proto_net_addr_proto_goTypes = nil
	file_proto_net_addr_proto_depIdxs = nil
}
